# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener: force
#    allowed_methods_listener:  true
#    routing_loader: true
    view:
        view_response_listener:  true
    exception:
        codes:
#            Symfony\Component\Routing\Exception\ResourceNotFoundException: 404
        messages:
            FOS\RestBundle\Exception\InvalidParameterException: true

    format_listener:
        rules:
           - { path: ^/api, prefer_extension: false, fallback_format: json, priorities: [ json ] }
           - { path: ^/, priorities: ['text/html', '*/*'], fallback_format: html, prefer_extension: false }
    body_listener: true
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors